### PR TITLE
ctrl-c handler

### PR DESCRIPTION
**Pull request by ondra-m**
Just an idea for #14

### CODE REVIEW

**Comment by piotrmurach** [comment]
Hi Ondrej,

I agree with you on the exit code removal, that's pretty much down to the client how to handle the escape key. I'm wondering whether we really need to send the signal at all(e.i. remove the line altogether)? I mean, ruby by default when `ctrl+c` is pressed will send interrupt signal, and so it would be down to consumer of the library to trap/handle it?

**Comment by ondra-m** [comment]
Agree but if you remove line from reader then nothing happen. Ctrl+c will be meaningless key press.

**Comment by piotrmurach** [comment]
The problem with killing processes is that jruby doesn't support Process#pid and I'm not sure how well signals are supported on windows. Do you think that instead of signalling we could just raise an error (TerminateInputError)? For example, IRB raises Abort error when interrupt signal is raised.

**Comment by ondra-m** [comment]
What about new setting?

```ruby
handler = nil  # nothing happen
handler = :send_sigterm  # like this merge
handler = :terminate_input  # raise an error
handler = :exit  # exit(130)
handler = proc {}  # custom

prompt = TTY::Prompt.new(sigterm_handler: handler)
```

**Comment by piotrmurach** [comment]
Like it a lot. I would probably call the setting `:interrupt_handler` to express its generic nature? I'm still thinking of using error as the default behaviour, that will ensure it works across systems and ruby implementations. Would you agree? If you have a minute to submit PR that would be sweet.

**Comment by piotrmurach** [comment]
Hi, I've documented api in [interrupt section](https://github.com/piotrmurach/tty-prompt#2212-interrupt) based on our discussions. Released `v0.7.0`.

**Comment by ondra-m** [comment]
Look good but I think that `interrupt: nil` is better than `:noop`.

**Comment by piotrmurach** [comment]
I usually stray away from `nil` at all costs. It doesn't carry meaning, doesn't provide good failures and most importantly I prefer things to be explicit. Even during testing this feature I've passed `options[:interrupt]` to reader as value and got bitten by `nil`. I want to spare myself and others misery by forcing specific value.

**Pull request merged**
