### PR TITLE
Add the ability to provide an arbitrary array of values to Prompt::Slider

### PR DESCRIPTION
**Pull request by slowbro**
Add the ability to provide an arbitrary array of values to Prompt::Slider, overriding the automatic min,max,step calculation.

### Example 
```ruby
require 'tty-prompt'

p = TTY::Prompt.new

apertures = ["f/2.8", "f/3.2", "f/3.5", "f/4", "f/4.5", "f/5", "f/5.6", "f/6.3", "f/7.1", "f/8", "f/9", "f/10", "f/11", "f/13", "f/14", "f/16", "f/18", "f/20", "f/22", "f/25", "f/29", "f/32"]

ans = p.slider( "Select an aperature value.", values: apertures ) do |sl|
  sl.default "f/4"
end

puts ans

class TestObj

  def initialize( name, value )
    @name = name
    @value = value
  end

  attr_reader :name
  attr_reader :value

  def to_s
    @name
  end

end

objs = [ TestObj.new( 'A', 'a' ), TestObj.new( 'B', 'b' ), TestObj.new( 'C', 'c' ) ]

ans = p.slider( "Select an aperature value.", values: objs )

puts ans.value
```

```
Select an aperature value. ───●────────────────── f/4
(Use ←/→ arrow keys, press Enter to select)
Select an aperature value. f/4
f/4
Select an aperature value. ─●─ B
(Use ←/→ arrow keys, press Enter to select)
Select an aperature value. B
b
```

### Describe the change
Allows giving arbitrary/pre-calculated, and String data to a Slider, to be slid through.

### Why are we doing this?
I had a specific need - selecting aperture and shutter speed values - that both included non-numeric values, and were irregularly spaced (so no valid `step` even if I remove the `/`).

### Benefits
I don't see any benefit to limiting Slider to numbers. This adds more capability to the library by supporting arbitrary data, including Objects that define `#to_s`!

### Drawbacks
The only backwards-compatibility issue I can think of would be changing the global `FORMAT` variable to use a string substitution instead of int/digit - but generally, ints translate to strings fine, so it should be okay. If one uses `:min`, `:max`, `:step`, it will still return an Integer.

### Requirements
Put an X between brackets on each line if you have done the item:
[x] Tests written & passing locally?
[x] Code style checked?
[x] Rebased with `master` branch?
[x] Documentation updated?

### CODE REVIEW

**Review by piotrmurach — COMMENTED** [review]
This is a great feature suggestion! I'm sold.

There is only one thing that I'm not sure about. You have kind of hinted at it in the documentation:

> If you'd rather not display all possible values in a vertical list, you may consider using `slider`.

I'm wondering if we could make this work without the need for `:values` option? This would make it more consistent with how other prompts like `select` work:

```ruby
prompt.slider("Letter", ('a'..'z').to_a)
```

As for DSL, we could potentially tap into the `Choice` and do:

```ruby
prompt.slider(""Select an aperature value.") do |q|
  q.default "f/3.2"
  q.choice "f/2.8"
  q.choice "f/3.2"
  q.choice "f/3.5"
end
```

And have more compact version as well:

```ruby
prompt.slider(""Select an aperature value.") do |q|
  q.default "f/3.2"
  q.choices "f/2.8", "f/3.2", "f/3.5
end
```

What do you reckon? I'm also curious about the command line tool you're building?

**Comment by slowbro** [comment]
Ah, I like that idea - you're right, it's much more consistent. I'll refactor that and get back to you!

--

The thing I'm making is a little control script/app using GPhoto2 for my DSLR which I'm using as my webcam for WFH: https://github.com/slowbro/camera-capture
Nothing super special, but it is nice to be able to adjust focus, aperture, etc without having to fiddle with the thing!

**Comment by slowbro** [comment]
Committed. I ended up using Choices for the numbers (min, max, step) as well. It should still be backwards-compatible! In this configuration, if you provide choices (either in prompt#slider, or via DSL) it will override any min/max/step you set (or the default).

I also made it possible to select the default by name or order (`default: 'f/2.8', or default: 1`), as by default it seems to be by-index.. at least in most places. This would be nice behavior elsewhere (i.e. select) - if you agree, I can make a separate PR to implement that.

**Comment by piotrmurach** [comment]
A pleasure to review and merge! Thank you❤️ 

I like your idea of extending default to accept both index and value - that would certainly improve the experience. 

---

I had a quick look at the `camera-capture` and I really like the idea - it looks super useful! I have Cannon as well and will give the script a try. Currently I'm learning photography but was thinking of using my camera for streaming as well. Have you thought about packaging the script and releasing it as a Ruby gem?

**Comment by slowbro** [comment]
Thanks for checking it out! I've actually never packaged my own gem before, but I plan on it! It would definitely be nice for dependency & putting the binary in one's PATH. I'm going to flesh out some of the core functionality around configurations before I do that, but it's definitely on the horizon!

**Comment by piotrmurach** [comment]
I often start by fleshing things out in a script with a corresponding test file. When things look promising, then I move my script code over to a gem. 

Once you have a minute you could consider using `tty` and the `teletype` for generating gem layout. Currently it piggy-backs on the Bundler gem but in the near future I want to generate things entirely from scratch. The [tty master branch](https://github.com/piotrmurach/tty) is the lastest unreleased implementation which I would appreciate help with. Your gem could be a good test bed. As for configuration [tty-config](https://github.com/piotrmurach/tty-config) is quite handy.

I will definietly add your gem to the [projects](https://ttytoolkit.org/projects/) section on ttytoolkit.org. I plan to change the current design so it doesn't require any project logos and try to add more projects so people can find repositories to learn/get inspired from.

**Comment by slowbro** [comment]
Ah, that's great! I will check out `teletype` and see how it works.

**Pull request merged**
